name: hyriver-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - setuptools

  # async_retriever
  - aiodns
  - aiohttp
  - aiohttp-client-cache
  - aiosqlite
  - brotlipy
  - chardet
  - cytoolz
  - nest-asyncio
  - orjson

  # pygeoogc deps
  # - cytoolz
  - defusedxml
  - owslib
  - pyproj
  - requests
  - requests_cache
  - shapely
  - simplejson

  # pygeoutils deps
  - geopandas
  - netCDF4
  - rasterio
  - xarray

  # pynhd deps
  - networkx
  - pyarrow

  # pygeohydro deps
  - folium
  - lxml
  - matplotlib-base
  - openpyxl

  # pydaymet deps
  # - lxml
  - dask-core
  - scipy

  # optional deps to speed up xarray and geopandas
  - bottleneck
  - rtree
  - pygeos

  # plotting deps
  - contextily
  - mapclassify
  - cartopy
  - colorcet

  # dev deps
  - setuptools_scm
  - pytest-xdist
  - pre-commit
  - flaky

  - pip
  - pip:
    - git+https://github.com/cheginit/async_retiriever.git
    - git+https://github.com/cheginit/pygeoogc.git
    - git+https://github.com/cheginit/pygeoutils.git
    - git+https://github.com/cheginit/pynhd.git
    - git+https://github.com/cheginit/py3dep.git
    - git+https://github.com/cheginit/pydaymet.git
    - git+https://github.com/cheginit/pygeohydro.git
